CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

IF(CMAKE_BUILD_TYPE MATCHES "Debug")
    SET(CACHALOT_BUILD_TYPE_DEBUG 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "RelWithDebInfo")
    SET(CACHALOT_BUILD_TYPE_RELWITHDEBINFO 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "Release")
    SET(CACHALOT_BUILD_TYPE_RELEASE 1)
ENDIF()

MACRO(ADD_FILTER group_name)
    SOURCE_GROUP(${group_name} FILES ${ARGN})
    SET(CACHALOT_SOURCE_FILES ${CACHALOT_SOURCE_FILES} ${ARGN})
ENDMACRO()